name: grocery_app
description: A comprehensive e-commerce grocery delivery mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design - Core essentials only
  cupertino_icons: ^1.0.6
  razorpay_flutter: ^1.3.6
  google_fonts: ^6.1.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.1.0
  shimmer: ^2.0.0
  lottie: ^1.4.3
  shared_preferences: ^2.2.2

  # State Management
  provider: ^6.0.5
  get: ^4.6.5

  # HTTP & API
  http: 1.4.0
  dio: ^4.0.6

  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Form & Validation
  form_field_validator: ^1.1.0
  email_validator: ^2.1.17

  # Navigation & Routing
  go_router: ^7.1.1

  # Image & Media
  image_picker: ^0.8.7+4
  photo_view: ^0.14.0

  # Utils
  intl: ^0.18.1
  uuid: ^3.0.7
  url_launcher: ^6.1.7
  path_provider: ^2.1.1
  permission_handler: ^11.0.1

  # Security
  crypto: ^3.0.3

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # OPTIONAL PLUGINS
  # mongo_dart: ^0.9.4
  # geolocator: ^8.2.1
  # geocoding: ^2.0.5
  # permission_handler: ^9.2.0
  # device_info_plus: ^8.2.2
  # package_info_plus: ^3.1.2
  # razorpay_flutter: ^1.3.2
  # firebase_core: ^2.10.0
  # firebase_messaging: ^14.4.1
  # connectivity_plus: ^3.0.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  hive_generator: ^1.1.3
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1  # Added for app icon generation

flutter:
  uses-material-design: true

  # Assets
  assets:
    - images/App_logo.jpg
    - images/App-logo.jpg
    - images/AppLogo.jpg
    - images/logo.png
    - images/google.png
    - images/facebook.jpeg

# App icon config
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

